fiber_test "Bad json tests"

json_fail ''
json_fail '  '
json_fail '{'
json_fail '[}'
json_fail '{true}'
json_fail 'nul'
json_fail 'true false'
json_fail '[true,]'
json_fail '[,]'
json_fail '[[[]],]'
json_fail '{,}'
json_fail '{:}'
json_fail '+0'
json_fail '+1'
json_fail '1.'
json_fail '.1'
json_fail '123ee'
json_fail '123e1.1'
json_fail '1 1'
