fiber_test "Bad json tests"

json_fail ''
json_fail '  '
json_fail '{'
json_fail '[}'
json_fail '{true}'
json_fail 'nul'
json_fail 'true false'
json_fail '[true,]'
json_fail '[,]'
json_fail '[[[]],]'
json_fail '{,}'
json_fail '{:}'
json_fail '+0'
json_fail '+1'
json_fail '1.'
json_fail '.1'
json_fail '123ee'
json_fail '123e1.1'
json_fail '1 1'
json_fail '"test'
json_fail '"test\\"'
json_fail '"test\nstring"'
json_fail '{"test"}'
json_fail '{"test":}'
json_fail '{"test":123,}'
json_fail '{"test",123}'
json_fail '{"test":123,"test5"}'
json_fail '{"test":123,"test5":}'
json_fail '{"test":123,"test5",}'
json_fail '{"test":123 "test5":false}'
json_fail '-.0'
json_fail '-0.0e+1.0'
json_fail '-0.0e-1.0'
json_fail '-'
json_fail '+'
json_fail '-1e'
json_fail '-e1'
json_fail '-1.e'
json_fail '-1e.'
json_fail '"abc":'
json_fail '"abc",'
json_fail '{123,123}'
